### ISSUE TITLE
Xvfb is frozen

### ISSUE THREAD

**Issue by bpinto** [leonid-shevtsov/headless#47]
Sometimes I receive this message when running `rspec`. And the only fix is to restart the computer.

I don't know the root cause yet, but running the Xvfb command headless runs without redirection, I get the following error:

````
➜ /opt/X11/bin/Xvfb :66636 -screen 0 1280x1024x24 -ac
_XSERVTransMakeAllCOTSServerListeners: failed to create listener for inet6
_XSERVTransMakeAllCOTSServerListeners: failed to create listener for inet
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
_XSERVTransSocketUNIXCreateListener: mkdir(/tmp/.X11-unix) failed, errno = 2
_XSERVTransMakeAllCOTSServerListeners: failed to create listener for local
(EE)
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
````

The manual solution is to run the following:
````
mkdir /tmp/.X11-unix
sudo chmod 1777 /tmp/.X11-unix
sudo chown root /tmp/.X11-unix/
````

**Comment by bensomers** [comment]
I encountered this error as a thundering-herd problem while trying to spin up a large number of Headless sessions concurrently (in different processes). The Headless sessions were timing out while trying to find a display to use - they were each starting at :99, then :100, etc., but it was taking too long for them to count up to an available display.

I fixed the issue with a very simple initializer:
````
# monkeypatch to fix a thundering-herd problem associated w/ Xvfb startup
# test the possible displays in a random order, instead of from the start, every time
class Headless

private

  def attach_xvfb
    possible_display_set = @autopick_display ? @display..MAX_DISPLAY_NUMBER : Array(@display)
    pick_available_display(possible_display_set.to_a.shuffle, @reuse_display)
  end

end
````

I am happy to put this into a pull-request if @leonid-shevtsov is amenable - it's a little more complicated than just copying the code over, as it breaks a whole bunch of tests that assume we're always looking for display :99.

**Comment by nitnagpal** [comment]
I encountered the same error and was able to reproduce it.
This error in my case was coming when the Xvfb process is still running but the lock file gets deleted somehow.
So the next time you do Headless.new it will try to launch new Xvfb by calling launch_xvfb which will fail giving below error because Xvfb is already running (Output of running Xvfb command /usr/bin/Xvfb :99 -screen 0 1280x1024x24 -ac)

_XSERVTransSocketINETCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE) 
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)

The above Xvfb command will fail and not create the new lock file and will also skip the "Xvfb did not launch - something's wrong" exception because "unless result" will be false. So ensure_xvfb_is_running will keep on failing the xvfb_running? test because of missing lock file and at last will throw "Xvfb is frozen" after XVFB_LAUNCH_TIMEOUT

Hope this might help somebody having the same scenario.

**Comment by leonid-shevtsov** [comment]
I made some changes that should fix or at least help debug this problem. Please upgrade to headless version 2.0.0 and see if the issue persists.

**Comment by paulkernfeld** [comment]
Hey @leonid-shevtsov, could you point me to the commit that solved this problem? The node version of headless is seeing the same issue ([here](https://github.com/kesla/node-headless/issues/23)).

**Comment by leonid-shevtsov** [comment]
@paulkernfeld There's a node version of headless? Wow, didn't know that!

Here's the commit - IIRC the change was to start Xvfb with Process.spawn https://github.com/leonid-shevtsov/headless/commit/2886098dbf9a6ac63045a4a1fb8de40f03d5b67f

**Comment by zzolcsak** [comment]
When I've got this error, my issue was that I was logging in through a Putty session that had X11 forwarding enabled. When I changed this setting, I could successfully start the Xvfb server.
